### ISSUE TITLE
request.on not working

### ISSUE THREAD

**Issue by SupremeTechnopriest** [camshaft/superagent-defaults#10]
I want some global error handling with superagent and I can't even get a simple log to work.

ignore the es6. it gets transpiled. 

```javascript

// RequestDefaults.js
import defaults from 'superagent-defaults';
const request = defaults();

request.on('error', (err) => { console.log(err) });

export default request
```

Then the subsequent request as usual:

```javascript

// APIUtils.js

import request from './RequestDefaults';
request
        .post(base + '/v1/login')
        .send({ alias: alias, password: password })
        .end(function(err, res){
            // Some stuff
        });
```
I would expect a `401` response to trigger the default log, but it does not.

EDIT:

Upon further investigation. It actually doesn't work at all. The request goes out, but **NO DEFAULTS ARE APPLIED.**  Im trying to export the default context after some configuration to be used across my application. Could that be the problem?

**Comment by camshaft** [comment]
error logging hasn't been implemented. feel free to add it :)

**Comment by SupremeTechnopriest** [comment]
@camshaft hmmm ive tried to use it with just setting a header too and the header does not get set.  Could there be some dependency collision?  I noticed you have `'superagent': *`  in `package.json`

**Comment by nathfy** [comment]
I can get the .set to work, but not .on - note the .use method works - so:
<pre>
request
    .set('X-CSRF-Token', document.getElementsByTagName('meta')['csrf-token'].getAttribute('content'))
    .use(function(req){
            console.log(req.url);
    });
</pre>

will return the url per request. Though I was hoping to be able to add a default .end to each request to look at the response, but seems not...

**Comment by SupremeTechnopriest** [comment]
@camshaft Hey, could you point me in the right direction to implement `end`?  I took a look at your code.  I don't see `end` being exempt from the `protoMethods` so not really sure why it's not working.

**Comment by camshaft** [comment]
I just updated the documentation to reflect the correct api. You can check the tests for more examples.
