### ISSUE TITLE
Support for superagent-proxy

### ISSUE THREAD

**Issue by zivc** [camshaft/superagent-defaults#12]
Hi,

I'm stuck behind a firewall, corporate/hotel/entertainment venue etc, and need to get `superagent` to obey proxy settings. Is it possible this could be extended and add support for `superagent-proxy` so we can define a proxy once as a default?

Many thanks,

Ash

**Comment by camshaft** [comment]
you can always bind to the `request` event and modify the request object:

```
var superagent = defaults();
superagent
  .on('request', function (req) {
    req.proxy('...');
  });
```

**Comment by zivc** [comment]
Thanks @camshaft
