### ISSUE TITLE
Can't return in promise resolve

### ISSUE THREAD

**Issue by flippidippi** [camshaft/superagent-defaults#18]
I'm trying to create a wrapper for superagent with defaults with an authorization header from a callout like:

```javascript
module.exports = () =>
  new Promise((resolve, reject) => {
    superagent
      .post('https://blah.com/session')
      .send({
        user: 'blah',
        pass: 'blah'
      })
      .then(result => {
        let api = Defaults()
        let base = Prefix('blah')

        api
          .use(base)
          .set({
            'Authorization': result.body.auth_token,
            'Accept': 'application/json'
          })

        resolve(api)
      })
      .catch(err => {
        console.log('api login failed')
        reject(err)
      })
  })
```

But when I try to use it like below, it successfully gets to the `resolve(api)` line but never gets to the `conn.get` line.
```
api()
  .then(conn => conn.get('/test'))
```

If I do the same just resolving with `superagent` without defaults it works. Not sure what's going on 😢

**Comment by supertong** [comment]
I got the same problem. Do you have a solution for it already? @flipxfx

**Comment by flippidippi** [comment]
I switched libraries 🙁

**Comment by supertong** [comment]
Thanks for replying @flipxfx . What library did you end up using? I am basically using `supertest` for my integration testing.
Just in case other people hits this issue. I found a work around for the issue. It was because the object has a `.then()` function in the prototype.
```
const request = default(app);
request.then = undefined;
```
The above code worked around my issue.

**Comment by flippidippi** [comment]
I use axios, wreck or apollo-client now.
