### ISSUE TITLE
wish: supertest support

### ISSUE THREAD

**Issue by markstos** [camshaft/superagent-defaults#2]
Thanks for the useful addition to superagent

It would be useful it could accept the class to modify as an option, so I could use it to extend `supertest` as well as `superagent`. The class to modify could still default to `superagent`.

For some related context, Perl has the problem with it's popular web-browser, LWP::UserAgent, which had lots of extensions by sub-classing. In many cases like this one, you could not combine two useful extension because of the way that LWP::UserAgent was extended.  I wrote about that here:

http://perl.qa.narkive.com/pahziYsb/interest-in-converting-lwp-mech-hierarchy-to-roles

If `superagent` was instead extended through traits or mixins, then those traits could be applied to other classes and still work. Even better, people could apply multiple extensions as they wish. In node.js,  Joose.js implements Traits like Perl's Moose roles, and Cocktail.js is another alternative for traits. I haven't looked closely about whether they would be a viable pattern to use for your particular extension.

**Comment by Zertz** [comment]
@hellboy81 See PR #9
